# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'ui/new_case.ui'
#
# Created by: PyQt5 UI code generator 5.15.4
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt5 import QtCore, QtGui, QtWidgets
from PyQt5.QtWidgets import QMessageBox,QApplication,QMainWindow,QWidget,QDialog,QVBoxLayout,QFileDialog
from open_case_window import *
from os import mkdir,getcwd
from hashlib import md5
from shutil import copyfile
from keras.utils import image_utils
from keras.models import load_model

class new_case_Ui(object):
    def __init__(self):
        super().__init__()
        

    def setupUi(self, Form):
        Form.setObjectName("Form")
        Form.resize(526, 485)
        icon = QtGui.QIcon()
        icon.addPixmap(QtGui.QPixmap("ui/resources/doctor.png"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        Form.setWindowIcon(icon)
        self.submit_button = QtWidgets.QPushButton(Form)
        self.submit_button.setGeometry(QtCore.QRect(300, 440, 87, 27))
        self.submit_button.setObjectName("submit_button")
        self.line = QtWidgets.QFrame(Form)
        self.line.setGeometry(QtCore.QRect(170, 30, 20, 351))
        self.line.setFrameShape(QtWidgets.QFrame.VLine)
        self.line.setFrameShadow(QtWidgets.QFrame.Sunken)
        self.line.setObjectName("line")
        
        
        
        
        ############################################
        self.under_med_label = QtWidgets.QLabel(Form)
        self.under_med_label.setGeometry(QtCore.QRect(40, 190, 141, 19))
        self.under_med_label.setObjectName("under_med_label")
        self.under_med_input = QtWidgets.QComboBox(Form)
        self.under_med_input.setGeometry(QtCore.QRect(190, 190, 79, 27))
        self.under_med_input.setObjectName("under_med_input")
        self.under_med_input.addItems(["Yes","No"])
        self.under_med_input.setCurrentText("No")
        ############################################
        self.bd_label = QtWidgets.QLabel(Form)
        self.bd_label.setGeometry(QtCore.QRect(40, 70, 91, 19))
        self.bd_label.setObjectName("bd_label")
        self.bd_input = QtWidgets.QDateEdit(Form)
        self.bd_input.setGeometry(QtCore.QRect(190, 70, 110, 27))
        self.bd_input.setObjectName("bd_input")
        
        
        ############################################
        self.days_since_infected_label = QtWidgets.QLabel(Form)
        self.days_since_infected_label.setGeometry(QtCore.QRect(40, 310, 141, 21))
        self.days_since_infected_label.setObjectName("days_since_infected_label")
        self.days_since_infected_input = QtWidgets.QSpinBox(Form)
        self.days_since_infected_input.setGeometry(QtCore.QRect(190, 310, 81, 27))
        self.days_since_infected_input.setObjectName("days_since_infected_input")
        ############################################
        self.upload_image = QtWidgets.QPushButton(Form)
        self.upload_image.setGeometry(QtCore.QRect(180, 400, 121, 27))
        self.upload_image.setObjectName("upload_image")
        ############################################
        self.cancel_button = QtWidgets.QPushButton(Form)
        self.cancel_button.setGeometry(QtCore.QRect(400, 440, 87, 27))
        self.cancel_button.setObjectName("cancel_button")
        ############################################
        self.hyperten_label = QtWidgets.QLabel(Form)
        self.hyperten_label.setGeometry(QtCore.QRect(40, 230, 101, 19))
        self.hyperten_label.setObjectName("hyperten_label")
        self.hyperten_input = QtWidgets.QComboBox(Form)
        self.hyperten_input.setGeometry(QtCore.QRect(190, 230, 79, 27))
        self.hyperten_input.setObjectName("hyperten_input")
        self.hyperten_input.addItems(["Yes","No"])
        self.hyperten_input.setCurrentText("No")
        ############################################
        self.name_label = QtWidgets.QLabel(Form)
        self.name_label.setGeometry(QtCore.QRect(40, 30, 66, 19))
        self.name_label.setObjectName("name_label")
        self.name_input = QtWidgets.QLineEdit(Form)
        self.name_input.setGeometry(QtCore.QRect(190, 30, 271, 21))
        self.name_input.setObjectName("name_input")
        ############################################
        self.gender_label = QtWidgets.QLabel(Form)
        self.gender_label.setGeometry(QtCore.QRect(40, 110, 61, 19))
        self.gender_label.setObjectName("gender_label")
        self.gender_input = QtWidgets.QComboBox(Form)
        self.gender_input.setGeometry(QtCore.QRect(190, 110, 111, 27))
        self.gender_input.setMaxVisibleItems(3)
        self.gender_input.setObjectName("gender_input")
        self.gender_input.addItems(["Male","Female"])
        self.gender_input.setCurrentText("Male")
        ############################################
        self.samrt_scan_for_label = QtWidgets.QLabel(Form)
        self.samrt_scan_for_label.setGeometry(QtCore.QRect(40, 270, 121, 19))
        self.samrt_scan_for_label.setObjectName("samrt_scan_for_label")
        self.smart_scan_for_input = QtWidgets.QComboBox(Form)
        self.smart_scan_for_input.setGeometry(QtCore.QRect(190, 270, 200, 27))
        self.smart_scan_for_input.setObjectName("smart_scan_for_input")
        self.smart_scan_for_input.addItems(["Dermatological lesions","Skin tumors"])
        self.smart_scan_for_input.setCurrentText("Dermatological lesions")
        ############################################
        self.email_label = QtWidgets.QLabel(Form)
        self.email_label.setGeometry(QtCore.QRect(40, 150, 66, 19))
        self.email_label.setObjectName("email_label")
        self.email_input = QtWidgets.QLineEdit(Form)
        self.email_input.setGeometry(QtCore.QRect(190, 150, 271, 21))
        self.email_input.setInputMethodHints(QtCore.Qt.ImhEmailCharactersOnly)
        self.email_input.setObjectName("email_input")
        ############################################
        self.phone_lable = QtWidgets.QLabel(Form)
        self.phone_lable.setGeometry(QtCore.QRect(40, 350, 66, 19))
        self.phone_lable.setObjectName("phone_lable")
        self.phone_input = QtWidgets.QLineEdit(Form)
        self.phone_input.setGeometry(QtCore.QRect(190, 350, 161, 21))
        self.phone_input.setInputMethodHints(QtCore.Qt.ImhEmailCharactersOnly)
        self.phone_input.setObjectName("phone_input")

        self.retranslateUi(Form)
        

        self.cancel_button.clicked.connect(Form.close)
        self.submit_button.clicked.connect(self.makecase)
        self.submit_button.clicked.connect(Form.close)
        self.upload_image.clicked.connect(lambda : self.upload_image_func())
        QtCore.QMetaObject.connectSlotsByName(Form)

        
    def get_info(self):
        name     = self.name_input.text()
        phone    = self.phone_input.text()
        email    = self.email_input.text()
        bd       = self.bd_input.date().toPyDate()
        gender   = self.gender_input.currentText()
        scanType = self.smart_scan_for_input.currentText()
        hyperten = self.hyperten_input.currentText()
        underMed = self.under_med_input.currentText()
        infecteddays= self.days_since_infected_input.value()
        return [name,phone,email,str(bd),gender,scanType,hyperten,underMed,str(infecteddays)]


    def retranslateUi(self, Form):
        _translate = QtCore.QCoreApplication.translate
        Form.setWindowTitle(_translate("Form", "New case"))
        self.submit_button.setText(_translate("Form", "Submit"))
        self.name_label.setText(_translate("Form", "Name:"))
        self.bd_label.setText(_translate("Form", "Date of birth:"))
        self.days_since_infected_label.setText(_translate("Form", "Days since infected:"))
        self.under_med_label.setText(_translate("Form", "Under medication:"))
        self.bd_input.setDisplayFormat(_translate("Form", "dd/MM/yyyy"))
        self.gender_label.setText(_translate("Form", "Gender:"))
        self.upload_image.setText(_translate("Form", "Upload image"))
        self.cancel_button.setText(_translate("Form", "Cancel"))
        self.hyperten_label.setText(_translate("Form", "Hypertention:"))
        self.samrt_scan_for_label.setText(_translate("Form", "Smart scan for:"))
        self.email_label.setText(_translate("Form", "Email:"))
        self.phone_lable.setText(_translate("Form", "Phone:"))



    def upload_image_func(self):
        filename=QFileDialog.getOpenFileName()
        global path
        path=filename[0]
        path=str(path)
        target_size=(64,64)
        model=load_model('skin_cancer_classfication_64_input_2conv_64_64_3dense_dropout=_2.h5')
        global result
        result=self.predict_class(path,target_size,model) 
        # img_file=image.load_img(path,target_size=(224,224))
        # x=image.img_to_array(img_file)
        # x=np.expand_dims(x, axis=0)
        # img_data=preprocess_input(x)
        # classes=model.predict(img_data)
        
        # self.makecase()
    
    def predict_class(self,path,target_size,model):
        img = image_utils.load_img(path,target_size=target_size)
        # img.getpixel
        # plt.imshow(img)
        img = image_utils.img_to_array(img)
        img = img.reshape((1,) + img.shape)
        
        result = model.predict(img)
        if result[0][0] == 0:
            return 'benign'
        elif result[0][0] == 1:
            return 'malignant'


    def makecase(self):
        info = self.get_info()
        imageName= path.split("/")[-1]
        newpath=getcwd()+"/Cases/"+ info[0] #md5(' '.join(info).encode()).hexdigest()
        mkdir(newpath)
        copyfile(path,newpath+"/"+imageName)
        info.append(newpath+"/"+imageName)
        info.append(result)
        file=open(newpath+"/case.txt","w")
        for element in info:
            file.write(element+"\n")
        file.close()
        
        self.w = QWidget()
        ui=open_case_window()
        ui.setupUi(self.w,info)
        self.w.show()
        